Expanded IFacade hook
Chisel-Team/Chisel pull request #414
Opened 2017-04-22 12:37 UTC by CreativeMD

Hey,

I finally found some time and tried to implement connected textures for LittleTiles (https://github.com/Chisel-Team/Chisel/issues/378). After reading some of your code, I spotted an interface which would allow me to implement exactly what i want: `IFacade`. Unfortunately, one parameter is missing, since there can be all kind of different block types inside one of my blocks and i don't know which one to return. So i added a `neighbor` parameter, which i can use to check if that block state can be found inside my block or not.

In Regards
CreativeMD

2017-04-23 16:32 UTC, tterrag1098 requested changes
I think this change is ok, but I worry that it might still be too limited. For instance, what if you want to know more than state info about the block you're connecting to, such as TE or extended state data? This is going to be an API breaking change, so I want to make it worthwhile.

2017-04-23 16:32 UTC, tterrag1098 commented on src/main/java/team/chisel/api/IFacade.java
> +    IBlockState getFacade(@Nonnull IBlockAccess world, @Nonnull BlockPos pos, @Nullable EnumFacing side, IBlockState neighbor);
This param should be `@Nonnull`

2017-04-23 16:45 UTC, CreativeMD commented
I have not thought about it in that way. I don't plan to implement any calculations to check whether the two blocks connect directly or not. From my experience the required performance is not worth it and most of the times you want the textures to connect even if the tiles aren't placed next to each other.

2017-04-25 14:13 UTC, HenryLoenwind commented
If you add the new methods instead of replacing the old and then wrap the call in a try-catch block for ---whatsitcalled? AbstractMethodException?--- with the old one as fallback, this change will not be breaking. On the other hand, does anyone consume this API in 1.11 atm?

Then is the question on whether this change goes far enough. 

```
/**
Returns:
<li>null to force the other block to connect textures
<li>Blocks.AIR.getDefaultBlockstate() to force the other block to NOT connect textures
<li>the blockstate the block exposed at the given location, the caller decides on connecting or not
**/
IBlockState getFacade(@Nonnull IBlockAccess world, @Nonnull BlockPos pos, @Nullable FacadeSide side, @Nullable IBlockState neighborState)
...

enum FacadeSide {
DOWN, UP, EAST, WEST, SOUTH, NORTH, // the center of those faces
DOWN_EAST. DOWN_WEST, DOWN_SOUTH, DOWN_NORTH, // the 4 edges of the down side
UP_EAST. UP_WEST, UP_SOUTH, UP_NORTH, // the 4 edges of the up side
EAST_DOWN EAST_UP, EAST_SOUTH, EAST_NORTH, // the 4 edges of the up side
...
DOWN_EAST_NORTH, DOWN_EAST_SOUTH, DOWN_WEST_NORTH, DOWN_WEST_SOUTH, // the 4 corner of the down side,
...
// add methods to get the data from the names, getBaseSide, isEdge, isCorner, getEdgeDirection...

```

2017-04-25 17:57 UTC, tterrag1098 commented
@HenryLoenwind the API you are describing there already exists. I was thinking something along the lines of 

```java
IBlockState getFacade(IBlockAccess world, BlockPos pos, EnumFacing side, Dir connection);
```

Where `Dir` is this class https://github.com/Chisel-Team/Chisel/blob/1.10/dev/src/main/java/team/chisel/common/util/Dir.java

The shortcoming of this is determining facade state for a non-ctm render, such as pillars, where the connecting state may not even be adjacent to the given block.

2017-04-25 18:13 UTC, HenryLoenwind commented
That Dir is basically the same as the enum I posted, just without the base EnumFacing. But you have the headache of having to find out what the "left" side of the bottom face of a block is.

2017-04-25 18:16 UTC, tterrag1098 commented
There is already code to offset a blockpos, so that's not an issue

On Apr 25, 2017 2:13 PM, "Henry Loenwind" <notifications@github.com> wrote:

> That Dir is basically the same as the enum I posted, just without the base
> EnumFacing. But you have the headache of having to find out what the "left"
> side of the bottom face of a block is.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Chisel-Team/Chisel/pull/414#issuecomment-297118535>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADk-8Lt0K3i-I9kUWGNNN9fjKJ1ilC7Jks5rzjfBgaJpZM4NFEuK>
> .
>

2017-04-26 10:23 UTC, CreativeMD commented
Ok, i added a Dir parameter as well (not if this will work out though).

2017-04-26 18:17 UTC, tterrag1098 commented
The problem is, as mentioned above, the connection might not always be representable by a `Dir`. For instance in the case of pillars, they require knowledge about blocks which are 2 units away. So I think, instead of using an enum of any kind, just providing the second location (as a `BlockPos`) would be the best course of action. Perhaps providing a utility to turn that into a `Dir` if the API user would find that useful.

I think I will handle this change myself, as it will involve reworking some API classes.

2017-04-29 19:07 UTC, CreativeMD commented
So i will close this pr. Just comment on the issue if there are any updates.

2017-04-29 19:07 UTC, closed without merging